# Generated by Django 2.0.2 on 2018-03-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainTransLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FromUserName', models.CharField(max_length=100)),
                ('CreateTime', models.CharField(max_length=30)),
                ('MsgType', models.CharField(max_length=20)),
                ('MsgId', models.CharField(max_length=70)),
                ('TransTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
