# Generated by Django 2.0.2 on 2018-03-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WX_FUNC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityList',
            fields=[
                ('CityName', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CityURL', models.CharField(max_length=50)),
            ],
        ),
    ]
