# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WX_FUNC', '0003_userlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=40)),
                ('RobotType', models.CharField(max_length=2)),
                ('TransTime', models.DateTimeField(auto_now_add=True)),
                ('MsgType', models.CharField(max_length=20)),
                ('ReqDict', models.CharField(max_length=2000)),
                ('RspDict', models.CharField(max_length=2000)),
            ],
        ),
    ]
