# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-12 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('channel', models.CharField(max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('suggest', models.CharField(max_length=1000)),
                ('dealflag', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=130)),
                ('level', models.CharField(max_length=1)),
                ('last_login_time', models.DateTimeField()),
                ('now_login_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
