# Generated by Django 2.0.2 on 2018-02-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_FUNC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='dealflag',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
