# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-17 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_FUNC', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
